# Generated by Django 3.2.13 on 2023-01-18 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicyearid', models.CharField(default=51120, max_length=10)),
                ('academicyear', models.IntegerField(choices=[(2023, 2023), (2024, 2024), (2025, 2025)], verbose_name='Academic Year')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectid', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Subject ID')),
                ('subjectname', models.CharField(max_length=50, verbose_name='Subject')),
                ('grade', models.CharField(choices=[(3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termid', models.CharField(default=932, max_length=20)),
                ('order', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='Term')),
                ('date_start', models.DateField(verbose_name='Term Commence')),
                ('date_end', models.DateField(verbose_name='Term End')),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('academicyearid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Week')),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('termid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap.term')),
            ],
        ),
    ]
