# Generated by Django 3.2.13 on 2023-01-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='academicyearid',
            field=models.CharField(default=48541, max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectname',
            field=models.CharField(choices=[('English', 'English'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Social Science', 'Social Science'), ('Arts', 'Arts')], max_length=50, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='term',
            name='termid',
            field=models.CharField(default=408, max_length=20),
        ),
    ]
