# Generated by Django 3.2.13 on 2023-01-18 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0002_auto_20230118_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='academicyearid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sap.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='totalscore',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='academicyearid',
            field=models.CharField(default=78661, max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectid',
            field=models.CharField(default=42204, max_length=7, primary_key=True, serialize=False, verbose_name='Subject ID'),
        ),
        migrations.AlterField(
            model_name='term',
            name='termid',
            field=models.CharField(default=876, max_length=20),
        ),
    ]
